export const TYPES = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    MULTIPLY: 'MULTIPLY',
    DIVIDE: 'DIVIDE',
    INCREMENT_5: 'INCREMENT_5',
    DECREMENT_5: 'DECREMENT_5',
    RESTART: 'RESTART'
}